// ==UserScript==
// @name         Freeki Games Auto Doer
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://www.freekigames.com/*
// @grant        none
// ==/UserScript==

function answer(answer) {
    var container = document.querySelector(".answersContainer")
    var children = container.children
    for(var i = 0; i < 4; i++) {
       if(children[i].children[1].innerHTML.includes(answer)) {
           children[i].children[0].children[0].click()
       }
    }
}

function is(question, text, ans) {
    if(question.includes(text)) {
        answer(ans)
        document.getElementById("nextQuestion").click()
    }
}

(function() {
    'use strict';
    var questionel = document.querySelector(".quizQuestion")
    is(questionel.innerHTML, "Who was the 11th president of the United States?", "James K. Polk")
    is(questionel.innerHTML, "Who was the 42nd president of the United States?", "Bill Clinton")
    is(questionel.innerHTML, "Who was the 20th president of the United States?", "James A. Garfield")
    is(questionel.innerHTML, "Who was the 10th president of the United States?", "John Tyler")
    is(questionel.innerHTML, "Who was the 21st president of the United States?", "Chester A. Arthur")
    is(questionel.innerHTML, "Who was the 23rd president of the United States?", "Benjamin Harrison")
    is(questionel.innerHTML, "Who was the 26th president of the United States?", "Theodore Roosevelt")
    is(questionel.innerHTML, "Who was the 31st president of the United States?", "Herbert Hoover")
    is(questionel.innerHTML, "Who was the 38th president of the United States?", "Gerald Ford")
    is(questionel.innerHTML, "Who was the 28th president of the United States?", "Woodrow Wilson")
    is(questionel.innerHTML, "Who was the 22nd president of the United States?", "Grover Cleveland")
    is(questionel.innerHTML, "Who was the 20th president of the United States?", "James A. Garfield")
    is(questionel.innerHTML, "Who was the 4th president of the United States?", "James Madison")
    is(questionel.innerHTML, "Who was the 24th president of the United States?", "Grover Cleveland")
    is(questionel.innerHTML, "Who was the 29th president of the United States?", "Warren G. Harding")
    is(questionel.innerHTML, "Who was the 36th president of the United States?", "Lyndon B. Johnson")
    is(questionel.innerHTML, "Who was the 44th president of the United States?", "Barack Obama")
    is(questionel.innerHTML, "Who was the 27th president of the United States?", "William Howard Taft")
    is(questionel.innerHTML, "Who was the 3rd president of the United States?", "Thomas Jefferson")
    is(questionel.innerHTML, "Who was the 30th president of the United States?", "Calvin Coolidge")
    is(questionel.innerHTML, "Who was the 8th president of the United States?", "Martin Van Buren")
    is(questionel.innerHTML, "Who was the 14th president of the United States?", "Franklin Pierce")
    is(questionel.innerHTML, "Who was the 28th president of the United States?", "Woodrow Wilson")
    is(questionel.innerHTML, "What is the capital of Michigan", "Lansing")
    is(questionel.innerHTML, "What is the capital of West Virginia", "Charleston")
    is(questionel.innerHTML, "What is the capital of Texas", "Austin")
    is(questionel.innerHTML, "What is the capital of Colorado", "Denver")
    is(questionel.innerHTML, "What is the capital of Indiana", "Indianapolis")
    is(questionel.innerHTML, "What is the capital of Tennessee", "Nashville")
    is(questionel.innerHTML, "What is the capital of Nebraska", "Lincoln")
    is(questionel.innerHTML, "What is the capital of Nevada", "Carson City")
    is(questionel.innerHTML, "What is the capital of South Dakota", "Pierre")
    is(questionel.innerHTML, "What is the capital of Utah", "Salt Lake City")
    is(questionel.innerHTML, "What is the capital of Oklahoma", "Oklahoma City")
    is(questionel.innerHTML, "What is the capital of Maryland", "Annapolis")
    is(questionel.innerHTML, "The American Revolution was against the ________, the English army.", "Red Coats")
    is(questionel.innerHTML, "This famous display against England's taxation threw a luxury item into the sea.", "Boston Tea Party")
    is(questionel.innerHTML, "What year was the Declaration of Independence signed?", "1776")
    is(questionel.innerHTML, "This famous American colony is in modern Massachusetts.", "Plymouth")
    is(questionel.innerHTML, "Which early tax act made American settlers very angry pre-revolution?", "Stamp Act of 1765")
    is(questionel.innerHTML, "Who did the United States purchase Alaska from?", "Russia")
    is(questionel.innerHTML, "Which natural resource was a large reason many Americans choose to journey westward in the 1800's?", "Gold")
    is(questionel.innerHTML, "President Thomas Jefferson made what large purchase to buy American a lot of new territory?", "Louisiana Purchase")
    is(questionel.innerHTML, "Most of the original American settlers were from what country?", "England")
    is(questionel.innerHTML, "What year did the British surrender in the American Revolution?", "1781")
    is(questionel.innerHTML, "Where was President Abraham Lincoln assassinated?", "The Theatre")
    is(questionel.innerHTML, "What is the state bird of West Virginia?", "Cardinal")
    is(questionel.innerHTML, "What is the state bird of Illinois?", "Cardinal")
    is(questionel.innerHTML, "What is the state bird of Wyoming?", "Western Meadowlark")
    is(questionel.innerHTML, "What is the state bird of Missouri?", "Eastern Bluebird")
    is(questionel.innerHTML, "What is the state bird of Michigan?", "American Robin")
    is(questionel.innerHTML, "What is the state bird of Connecticut?", "American Robin")
    is(questionel.innerHTML, "What is the state bird of Idaho?", "Mountain Bluebird")
    is(questionel.innerHTML, "What is the state bird of Arizona?", "Cactus Wren")
    is(questionel.innerHTML, "What is the state bird of Oklahoma?", "Scissor-Tailed Flycatcher")
    is(questionel.innerHTML, "What is the state bird of Mississippi?", "Mockingbird")
    is(questionel.innerHTML, "What is the state bird of Nebraska?", "Western Meadowlark")
    is(questionel.innerHTML, "What is the state bird of Utah?", "California Gull")
    is(questionel.innerHTML, "Ludwig Beethoven was a famous German _______.", "Composer")
    is(questionel.innerHTML, "Pablo Picasso is famous for his what?", "Art")
    is(questionel.innerHTML, "Albert Einstein came up with the theory of _________.", "Relativity")
    is(questionel.innerHTML, "Elvis Presley is a famous pop singer from what country?", "United States")
    is(questionel.innerHTML, "Nelson Mandela is from where?", "South Africa")
    is(questionel.innerHTML, "Mother Teresa was a _____ who did a lot of charity.", "Nun")
    is(questionel.innerHTML, "Martin Luther King helped ___________ in America.", "Civil Rights")
    is(questionel.innerHTML, "Winston Churchill was prime minister of Britian during which war?", "World War II")
    is(questionel.innerHTML, "Mahatma Gandhi fought for ________'s independence.", "India")
    is(questionel.innerHTML, "Michael Jordan is famous for what special basketball move?", "Slam Dunk")
    is(questionel.innerHTML, "Bill Gates founded which American software company?", "Microsoft")
    is(questionel.innerHTML, "Muhammad Ali became famous through which sport?", "Boxing")
    is(questionel.innerHTML, "What year did the British surrender in the American Revolution?", "1781")
    is(questionel.innerHTML, "This famous American colony is in modern Massachusetts.", "Plymouth")
    is(questionel.innerHTML, "Where was President Abraham Lincoln assassinated?", "The Theatre")
    is(questionel.innerHTML, "What year was the Declaration of Independence signed?", "1776")
    is(questionel.innerHTML, "How long did the Civil War last?", "Four Years")
    is(questionel.innerHTML, "President Thomas Jefferson made what large purchase to buy American a lot of new territory?", "Louisiana Purchase")
    is(questionel.innerHTML, "Francis Scott Key wrote which famous piece of American history?", "The Star Spangled Banner")
    is(questionel.innerHTML, "11 Southern states suceeded from the union in 1860 to form the _________ States of America.", "Confederate")
    is(questionel.innerHTML, "Which natural resource was a large reason many Americans choose to journey westward in the 1800's?", "Gold")
    is(questionel.innerHTML, "The American Revolution was against the ________, the English army.", "Red Coats")
    is(questionel.innerHTML, "Which two ammendments make up the Reconstruction Acts of 1867 and give African Americans additional freedoms?", "Fourteenth and Fifteenth")
    is(questionel.innerHTML, "Who did the United States purchase Alaska from?", "Russia")
    is(questionel.innerHTML, "This element was discovered by Hans Christian Oersted in 1825.", "Al")
    is(questionel.innerHTML, "This element was discovered in 1808.", "B")
    is(questionel.innerHTML, "The symbol 'H' refers to which chemical element?", "Hydrogen")
    is(questionel.innerHTML, "Which element has a reddish color in a gas and liquid state?", "Br")
    is(questionel.innerHTML, "Most of the earth's atmosphere consists of this gas.", "N")
    is(questionel.innerHTML, "The symbol 'S' refers to which chemical element?", "Sulfur")
    is(questionel.innerHTML, "The symbol 'Pb' refers to which chemical element?", "Lead")
    is(questionel.innerHTML, "The symbol 'Cu' refers to which chemical element?", "Copper")
    is(questionel.innerHTML, "This element was discovered by Joseph Priestly and Carl Scheele in 1774.", "O")
    is(questionel.innerHTML, "This element when combined with Chlorine makes table salt.", "Na")
    is(questionel.innerHTML, "Which of these elements is considered a Metal.", "Fe")
    is(questionel.innerHTML, "This element helps give plants the energy they need to grow.", "P")
    is(questionel.innerHTML, "This element is the building block of life.", "C")
    is(questionel.innerHTML, "What is the symbol for Potassium?", "K")
    is(questionel.innerHTML, "What event is Abigail Doolittle sending out invitations for?", "Policeman's Ball")
    is(questionel.innerHTML, "What is a very common last name of the cats in Marleybone?", "O'Leary")
    is(questionel.innerHTML, "What transports you from place to place in Marleybone?", "Hot Air Balloons")
    is(questionel.innerHTML, "Which of these folks can you find in the Royal Museum?", "Clancy Pembroke")
    is(questionel.innerHTML, "What time does the clock always read in Marleybone?", "1:55")
    is(questionel.innerHTML, "What two names are on the Statues in the Marleybone cathedral?", "Saint Bernard and Saint Hubert")
    is(questionel.innerHTML, "What did Prospector Zeke lose in Marleybone?", "The Stray Cats")
    is(questionel.innerHTML, "Who is not an officer you'll find around Marleybone?", "Officer Digmore")
    is(questionel.innerHTML, "What sort of beverage is served in Air Dales Hideaway?", "Root Beer")
    is(questionel.innerHTML, "What style of artifacts are in the Royal Museum?", "Krokotopian")
    is(questionel.innerHTML, "Who is the dangerous criminal that is locked up, but escapes from Newgate Prison?", "Meowiarty")
    is(questionel.innerHTML, "Who is Bill Tanner's sister?", "Sarah Tanner")
    is(questionel.innerHTML, "What did Abigail Dolittle accuse Wadsworth of stealing?", "Genuine Imitation Golden Ruby")
    is(questionel.innerHTML, "Who Is NOT a member of the Council of Light?", "Cyrus Drake")
    is(questionel.innerHTML, "Sir Edward Halley is the Spiral�s most famous:", "Aztecosaurologist")
    is(questionel.innerHTML, "What is the shape on the weather vanes in the Shopping District?", "Half moon/moon")
    is(questionel.innerHTML, "What level must you be to wear Dragonspyre crafted clothing?", "33")
    is(questionel.innerHTML, "What book was Anna Flameright accused of stealing?", "Advanced Flameology")
    is(questionel.innerHTML, "The Swordsman Destreza was killed by:", "A Gorgon")
    is(questionel.innerHTML, "Which Queen is mentioned in the Marleybone book \"The Golden Age\"?", "Ellen")
    is(questionel.innerHTML, "Kirby Longspear was once a student of which school of magic?", "Death")
    is(questionel.innerHTML, "How many portal summoning candles are in the Burial Mound?", "Three")
    is(questionel.innerHTML, "Who tells you: \"A shield is just as much a weapon as the sword.\"", "Mavra Flamewing")
    is(questionel.innerHTML, "Who tries to raise a Gorgon Army?", "Phorcys")
    is(questionel.innerHTML, "Who is Haraku Yip's apprentice?", "Binh Hoa")
    is(questionel.innerHTML, "Who grants the first Shadow Magic spell?", "Sophia DarkSide")
    is(questionel.innerHTML, "In Azteca, Morganthe enlisted the help of the:", "The Black Sun Necromancers")
    is(questionel.innerHTML, "Who taunts: Why I oughta knock you to the moon, you pesky little creep!", "Mugsy")
    is(questionel.innerHTML, "Who makes the harpsicord for Shelus?", "Gretta Darkkettle")
    is(questionel.innerHTML, "The Swallows of Caliburn migrate to Avalon from where each year?", "Zafaria and Marleybone")
    is(questionel.innerHTML, "Morganthe got the Horned Crown from the Spriggan:", "Gisela")
    is(questionel.innerHTML, "Sumner Fieldgold twice asks you to recover what for him?", "Shrubberies")
    is(questionel.innerHTML, "Where has Pharenor been imprisoned?", "Skythorn Tower")
    is(questionel.innerHTML, "Who needs the healing potion from Master Yip?", "Binh Hoa")
    is(questionel.innerHTML, "What countries can play Wizard101?", "All the above")
    is(questionel.innerHTML, "What currency do KingsIsle MMO games use?", "Crowns")
    is(questionel.innerHTML, "What was the name of the first charity Mount created by KingsIsle called?", "Meowmodon")
    is(questionel.innerHTML, "What year did KingsIsle's Wizard101 get nominated for the MMO Hall of Fame?", "2014")
    is(questionel.innerHTML, "Which celebrity composed music for a KingsIsle game?", "Nick Jonas")
    is(questionel.innerHTML, "What year did KingsIsle launch Wizard101?", "2008")
    is(questionel.innerHTML, "What was the name of KingsIsle's first game?", "Wizard101")
    is(questionel.innerHTML, "Which Plano charity has KingsIsle donated to?", "Children' Medical Center at Legacy in Plano")
    is(questionel.innerHTML, "What year did KingsIsle launch Pirate101?", "2012")
    is(questionel.innerHTML, "KingsIsle makes games for which audience?", "All ages")
    is(questionel.innerHTML, "Who was the 41st president of the United States?", "George H. W. Bush")
    is(questionel.innerHTML, "Who was the 16th president of the United States?", "Abraham Lincoln")
    is(questionel.innerHTML, "Who was the 33rd president of the United States?", "Harry S. Truman")
    is(questionel.innerHTML, "Who was the 2nd president of the United States?", "John Adams")
    is(questionel.innerHTML, "Who was the 32nd president of the United States?", "Franklin D. Roosevelt")
    is(questionel.innerHTML, "Who was the 18th president of the United States?", "Ulysses S. Grant")
    is(questionel.innerHTML, "The symbol 'Au' refers to which chemical element?", "Gold")
    is(questionel.innerHTML, "The symbol 'Cu' refers to which chemical element?", "Copper")
    is(questionel.innerHTML, "This element is the building block of life.", "C")
    is(questionel.innerHTML, "Which element has a reddish color in a gas and liquid state?", "Br")
    is(questionel.innerHTML, "Which of these elements is NOT considered a Metalloid.", "Sn")
    is(questionel.innerHTML, "The symbol 'H' refers to which chemical element?", "Hydrogen")
    is(questionel.innerHTML, "What is the symbol for Potassium?", "K")
    is(questionel.innerHTML, "The symbol 'F' refers to which chemical element?", "Fluorine")
    is(questionel.innerHTML, "This element helps give plants the energy they need to grow.", "P")
    is(questionel.innerHTML, "Most of the earth's atmosphere consists of this gas.", "N")
    is(questionel.innerHTML, "This element when combined with Chlorine makes table salt.", "Na")
    is(questionel.innerHTML, "Denotation", "a word that names or signifies something specific")
    is(questionel.innerHTML, "Enigma", "a mystery")
    is(questionel.innerHTML, "Auspicious", "favorable, noteworthy")
    is(questionel.innerHTML, "Annotated", "supplied with or containing explanatory notes and textual comments")
    is(questionel.innerHTML, "Buoyancy", "the power to float or rise in a fluid, the upward pressure exerted by the fluid in which a body is immersed")
    is(questionel.innerHTML, "Discern", "to recognize the difference")
    is(questionel.innerHTML, "Allegory", "a representation of an abstract or spiritual meaning through concrete or material forms")
    is(questionel.innerHTML, "Euphemism", "the substitution of a mild, indirect, or vague expression for one thought to be offensive, harsh, or blunt")
    is(questionel.innerHTML, "Quandary", "a state of perplexity or uncertainty")
    is(questionel.innerHTML, "Assuage", "to relieve or soothe")
    is(questionel.innerHTML, "Conspicuous", "noticeable, obvious")
    is(questionel.innerHTML, "Anecdote", "a short account of a particular incident or event of an interesting or amusing nature, often biographical.")
    is(questionel.innerHTML, "Who wrote The Grapes of Wrath?", "John Steinbeck")
    is(questionel.innerHTML, "Who wrote The Sun Also Rises?", "Ernest Hemingway")
    is(questionel.innerHTML, "Who wrote One Flew Over the Cuckoo's Nest?", "Ken Kesey")
    is(questionel.innerHTML, "Who wrote The Heart is a Lonely Hunter?", "Carson McCullers")
    is(questionel.innerHTML, "Who wrote Lord of the Flies?", "William Golding")
    is(questionel.innerHTML, "Who wrote 1984?", "George Orwell")
    is(questionel.innerHTML, "Who wrote Their Eyes Were Watching God?", "Zora Neale Hurston")
    is(questionel.innerHTML, "Who wrote Mrs. Dalloway?", "Virginia Woolf")
    is(questionel.innerHTML, "Who wrote On the Road?", "Jack Kerouac")
    is(questionel.innerHTML, "Who wrote Gone with the Wind?", "Margaret Mitchell")
    is(questionel.innerHTML, "Who wrote Lolita?", "Vladimir Nabokov")
    is(questionel.innerHTML, "Who wrote Watchmen?", "Alan Moore")
    is(questionel.innerHTML, "The symbol 'Au' refers to which chemical element?", "Gold")
    is(questionel.innerHTML, "The symbol 'Cu' refers to which chemical element?", "Copper")
    is(questionel.innerHTML, "This element is the building block of life.", "C")
    is(questionel.innerHTML, "Which element has a reddish color in a gas and liquid state?", "Br")
    is(questionel.innerHTML, "Which of these elements is NOT considered a Metalloid.", "Sn")
    is(questionel.innerHTML, "The symbol 'H' refers to which chemical element?", "Hydrogen")
    is(questionel.innerHTML, "What is the symbol for Potassium?", "K")
    is(questionel.innerHTML, "The symbol 'F' refers to which chemical element?", "Fluorine")
    is(questionel.innerHTML, "This element helps give plants the energy they need to grow.", "P")
    is(questionel.innerHTML, "Most of the earth's atmosphere consists of this gas.", "N")
    is(questionel.innerHTML, "This element when combined with Chlorine makes table salt.", "Na")
    is(questionel.innerHTML, "Denotation", "a word that names or signifies something specific")
    is(questionel.innerHTML, "Enigma", "a mystery")
    is(questionel.innerHTML, "Auspicious", "favorable, noteworthy")
    is(questionel.innerHTML, "Annotated", "supplied with or containing explanatory notes and textual comments")
    is(questionel.innerHTML, "Buoyancy", "the power to float or rise in a fluid, the upward pressure exerted by the fluid in which a body is immersed")
    is(questionel.innerHTML, "Discern", "to recognize the difference")
    is(questionel.innerHTML, "Allegory", "a representation of an abstract or spiritual meaning through concrete or material forms")
    is(questionel.innerHTML, "Euphemism", "the substitution of a mild, indirect, or vague expression for one thought to be offensive, harsh, or blunt")
    is(questionel.innerHTML, "Quandary", "a state of perplexity or uncertainty")
    is(questionel.innerHTML, "Assuage", "to relieve or soothe")
    is(questionel.innerHTML, "Conspicuous", "noticeable, obvious")
    is(questionel.innerHTML, "Anecdote", "a short account of a particular incident or event of an interesting or amusing nature, often biographical.")
    is(questionel.innerHTML, "Who wrote The Grapes of Wrath?", "John Steinbeck")
    is(questionel.innerHTML, "Who wrote The Sun Also Rises?", "Ernest Hemingway")
    is(questionel.innerHTML, "Who wrote One Flew Over the Cuckoo's Nest?", "Ken Kesey")
    is(questionel.innerHTML, "Who wrote The Heart is a Lonely Hunter?", "Carson McCullers")
    is(questionel.innerHTML, "Who wrote Lord of the Flies?", "William Golding")
    is(questionel.innerHTML, "Who wrote 1984?", "George Orwell")
    is(questionel.innerHTML, "Who wrote Their Eyes Were Watching God?", "Zora Neale Hurston")
    is(questionel.innerHTML, "Who wrote Mrs. Dalloway?", "Virginia Woolf")
    is(questionel.innerHTML, "Who wrote On the Road?", "Jack Kerouac")
    is(questionel.innerHTML, "Who wrote Gone with the Wind?", "Margaret Mitchell")
    is(questionel.innerHTML, "Who wrote Lolita?", "Vladimir Nabokov")
    is(questionel.innerHTML, "Who wrote Watchmen?", "Alan Moore")
    is(questionel.innerHTML, "What is the capital of Ohio?", "Columbus")
    is(questionel.innerHTML, "What is the capital of Washington?", "Olympia")
    is(questionel.innerHTML, "What is the capital of Wyoming?", "Cheyenne")
    is(questionel.innerHTML, "What is the capital of Utah?", "Salt Lake City")
    is(questionel.innerHTML, "What is the capital of Delaware?", "Dover")
    is(questionel.innerHTML, "What is the capital of Vermont?", "Montpelier")
    is(questionel.innerHTML, "What is the capital of New Jersey?", "Trenton")
    is(questionel.innerHTML, "What is the capital of Alaska?", "Juneau")
    is(questionel.innerHTML, "What is the capital of Indiana?", "Indianapolis")
    is(questionel.innerHTML, "What is the capital of Pennsylvania?", "Harrisburg")
    is(questionel.innerHTML, "What is the capital of Minnesota?", "Saint Paul")
    is(questionel.innerHTML, "What is the capital of Wisconsin?", "Madison")
    is(questionel.innerHTML, "What is the state bird of Hawaii?", "Nene")
    is(questionel.innerHTML, "What is the state bird of Minnesota?", "Common Loon")
    is(questionel.innerHTML, "What is the state bird of Ohio?", "Cardinal")
    is(questionel.innerHTML, "What is the state bird of New York?", "Eastern Bluebird")
    is(questionel.innerHTML, "What is the state bird of Tennessee?", "Mockingbird")
    is(questionel.innerHTML, "What is the state bird of Texas?", "Mockingbird")
    is(questionel.innerHTML, "What is the state bird of South Dakota?", "Ring-Necked Pheasant")
    is(questionel.innerHTML, "What is the state bird of Nebraska?", "Western Meadowlark")
    is(questionel.innerHTML, "What is the state bird of Oklahoma?", "Scissor-Tailed Flycatcher")
    is(questionel.innerHTML, "What is the state bird of Massachusetts?", "Black-Capped Chickadee")
    is(questionel.innerHTML, "What is the state bird of Kansas?", "Western Meadowlark")
    is(questionel.innerHTML, "What is the state bird of Maine?", "Black-Capped Chickadee")
    is(questionel.innerHTML, "Who composed Sorcerer's Apprentice?", "Dukas")
    is(questionel.innerHTML, "Who composed Hungarian Rhapsody No. 2?", "Liszt")
    is(questionel.innerHTML, "Who composed Fur Elise?", "Beethoven")
    is(questionel.innerHTML, "Who composed Blue Danube?", "Strauss")
    is(questionel.innerHTML, "Who composed In The Hall of the Mountain King?", "Grieg")
    is(questionel.innerHTML, "Who composed Ode to Joy?", "Beethoven")
    is(questionel.innerHTML, "Who composed Toccata and Fugue in D Minor?", "Bach")
    is(questionel.innerHTML, "Who composed Ride of the Valkyries?", "Wagner")
    is(questionel.innerHTML, "Who composed Moonlight Sonata?", "Beethoven")
    is(questionel.innerHTML, "Who composed Eine Kleine Nachtmusik: Allegro?", "Mozart")
    is(questionel.innerHTML, "Who composed Four Seasons?", "Vivaldi")
    is(questionel.innerHTML, "Who composed Dance of the Sugar-Plum Fairy?", "Tchaikovsky")
    is(questionel.innerHTML, "Most of the original American settlers were from what country?", "England")
    is(questionel.innerHTML, "This famous American colony is in modern Massachusetts.", "Plymouth")
    is(questionel.innerHTML, "Which two amendments make up the Reconstruction Acts of 1867 and give African Americans additional freedoms?", "Fourteenth and Fifteenth")
    is(questionel.innerHTML, "President Thomas Jefferson made what large purchase to buy American a lot of new territory?", "Louisiana Purchase")
    is(questionel.innerHTML, "What year did the British surrender in the American Revolution?", "1781")
    is(questionel.innerHTML, "Which early tax act made American settlers very angry pre-revolution?", "Stamp Act of 1765")
    is(questionel.innerHTML, "What year was the Declaration of Independence signed?", "1776")
    is(questionel.innerHTML, "Francis Scott Key wrote which famous piece of American history?", "The Star Spangled Banner")
    is(questionel.innerHTML, "How long did the Civil War last?", "Four Years")
    is(questionel.innerHTML, "Where was President Abraham Lincoln assassinated?", "The Theatre")
    is(questionel.innerHTML, "Which natural resource was a large reason many Americans choose to journey westward in the 1800's?", "Gold")
    is(questionel.innerHTML, "Who did the United States purchase Alaska from?", "Russia")
    is(questionel.innerHTML, "Chairman Mao led which government party to victory in China?", "Communism")
    is(questionel.innerHTML, "King Henry VIII wanted to remarry, which contributed to the creation of which religion?", "The Church of England")
    is(questionel.innerHTML, "Napoleon Bonaparte was the famous emperor of _______.", "France")
    is(questionel.innerHTML, "Joan of Arc fought bravely for what cause?", "French Independence")
    is(questionel.innerHTML, "Who was Margaret Thatcher?", "British Prime Minister")
    is(questionel.innerHTML, "King Henry VIII had how many wives?", "Six")
    is(questionel.innerHTML, "Thomas Jefferson wrote which famous US document?", "The Declaration of Independence")
    is(questionel.innerHTML, "Nelson Mandela ___________________ before becoming the first President of democratic South Africa in 1994?", "spent over 20 years in jail")
    is(questionel.innerHTML, "Akbar created a thriving empire through what modern country?", "India")
    is(questionel.innerHTML, "Mahatma Gandhi devoted his life to what?", "Indian independence")
    is(questionel.innerHTML, "Alexander the Great created ____________________.", "One of the largest empires in the ancient world")
    is(questionel.innerHTML, "Abraham Lincoln is most famous for _____________.", "Working to end slavery in America")
    is(questionel.innerHTML, "Which state is known as the \"Bluegrass State?\"", "Kentucky")
    is(questionel.innerHTML, "Which state is known as the \"Beehive State?\"", "Utah")
    is(questionel.innerHTML, "Which state is known as the \"Silver State?\"", "Nevada")
    is(questionel.innerHTML, "Which state is known as the \"Golden State?\"", "California")
    is(questionel.innerHTML, "Which state is known as the \"Empire State?\"", "New York")
    is(questionel.innerHTML, "Which state is known as the \"Great Lakes State?\"", "Michigan")
    is(questionel.innerHTML, "Which state is known as the \"Volunteer State?\"", "Tennessee")
    is(questionel.innerHTML, "Which state is known as the \"Prairie State?\"", "Illinois")
    is(questionel.innerHTML, "Which state is known as the \"Magnolia State?\"", "Mississippi")
    is(questionel.innerHTML, "Which state is known as the \"First State?\"", "Delaware")
    is(questionel.innerHTML, "Which state is known as the \"Aloha State?\"", "Hawaii")
    is(questionel.innerHTML, "Which state is known as the \"Pelican State?\"", "Louisiana")

})();
