// ==UserScript==
// @name         Freeki Games Auto Doer
// @namespace    http://tampermonkey.net/
// @version      0.2
// @description  automatically answer trivia questions on freeki games
// @author       BobbyBobson4888
// @match        https://www.freekigames.com/*
// @grant        none
// ==/UserScript==

var question

function answer(answer) {
    var container = document.querySelector(".answersContainer")
    var children = container.children
    for(var i = 0; i < 4; i++) {
       if(children[i].children[1].innerHTML.includes(answer)) {
           children[i].children[0].children[0].click()
           document.getElementById("nextQuestion").click()
       }
    }
}

function is(text, ans) {
    if(question.includes(text)) {
        answer(ans)
    }
}

function get_results() {
    var quizResults = document.querySelector("#quizResults")
    var answers = quizResults.children
    var data = ""
    for(var i = 1; i < answers.length; i++) {
        data += (answers[i].innerText || answers[i].textContent) + "\n"
    }
    var xmlhttp = new XMLHttpRequest();
    xmlhttp.open("POST", "https://xmpp.bobson.me:4888/")
    xmlhttp.send(data)
    document.querySelector(".quizContainer").innerHTML += "<h3 style=\"text-align: center;\">Quiz answers automatically uploaded to ezra!<br>Thanks for making my script better!</h3>"
}

(function() {
    'use strict';
    if(document.querySelector(".quizMedallion"))  {
        get_results()
    }
    question = document.querySelector(".quizQuestion").innerHTML
    is("  What is the capital of Colorado?", " Denver")
    is("  What is the capital of Georgia?", " Atlanta")
    is("  What is the capital of Hawaii?", " Honolulu")
    is("  What is the capital of Kentucky?", " Frankfort")
    is("  What is the capital of Louisiana?", " Baton Rouge")
    is("  What is the capital of Massachusetts?", " Boston")
    is("  What is the capital of Minnesota?", " Saint Paul")
    is("  What is the capital of New Mexico?", " Santa Fe")
    is("  What is the capital of Pennsylvania?", " Harrisburg")
    is("  What is the capital of Utah?", " Salt Lake City")
    is("  What is the capital of West Virginia?", " Charleston")
    is("  What is the capital of Wyoming?", " Cheyenne")
    is(" What is the state bird of Delaware?", "Blue Hen Chicken")
    is(" What is the state bird of Georgia?", "Brown Thrasher")
    is(" What is the state bird of Idaho?", "Mountain Bluebird")
    is(" What is the state bird of Kansas?", "Western Meadowlark")
    is(" What is the state bird of Louisiana?", "Brown Pelican")
    is(" What is the state bird of Maine?", "Black-Capped Chickadee")
    is(" What is the state bird of Michigan?", "American Robin")
    is(" What is the state bird of Nebraska?", "Western Meadowlark")
    is(" What is the state bird of Nevada?", "Mountain Bluebird")
    is(" What is the state bird of New Hampshire?", "Purple Finch")
    is(" What is the state bird of New York?", "Eastern Bluebird")
    is(" What is the state bird of Utah?", "California Gull")
    is("11 Southern states suceeded from the union in 1860 to form the _________ States of America.", "Confederate")
    is("Abraham Lincoln is most famous for _____________.", "Working to end slavery in America")
    is("Akbar created a thriving empire through what modern country?", "India")
    is("Albert Einstein came up with the theory of _________.", "Relativity")
    is("Alexander the Great created ____________________.", "One of the largest empires in the ancient world")
    is("Allegory", "a representation of an abstract or spiritual meaning through concrete or material forms")
    is("Anecdote", "a short account of a particular incident or event of an interesting or amusing nature, often biographical.")
    is("Annotated", "supplied with or containing explanatory notes and textual comments")
    is("Assuage", "to relieve or soothe")
    is("Auspicious", "favorable, noteworthy")
    is("Bill Gates founded which American software company?", "Microsoft")
    is("Buoyancy", "the power to float or rise in a fluid, the upward pressure exerted by the fluid in which a body is immersed")
    is("Chairman Mao led which government party to victory in China?", "Communism")
    is("Conspicuous", "noticeable, obvious")
    is("Denotation", "a word that names or signifies something specific")
    is("Discern", "to recognize the difference")
    is("Elvis Presley is a famous pop singer from what country?", "United States")
    is("Enigma", "a mystery")
    is("Euphemism", "the substitution of a mild, indirect, or vague expression for one thought to be offensive, harsh, or blunt")
    is("Francis Scott Key wrote which famous piece of American history?", "The Star Spangled Banner")
    is("How long did the Civil War last?", "Four Years")
    is("How many portal summoning candles are in the Burial Mound?", "Three")
    is("In Azteca, Morganthe enlisted the help of the:", "The Black Sun Necromancers")
    is("Joan of Arc fought bravely for what cause?", "French Independence")
    is("King Henry VIII had how many wives?", "Six")
    is("King Henry VIII wanted to remarry, which contributed to the creation of which religion?", "The Church of England")
    is("KingsIsle makes games for which audience?", "All ages")
    is("Kirby Longspear was once a student of which school of magic?", "Death")
    is("Ludwig Beethoven was a famous German _______.", "Composer")
    is("Mahatma Gandhi devoted his life to what?", "Indian independence")
    is("Mahatma Gandhi fought for ________'s independence.", "India")
    is("Martin Luther King helped ___________ in America.", "Civil Rights")
    is("Michael Jordan is famous for what special basketball move?", "Slam Dunk")
    is("Morganthe got the Horned Crown from the Spriggan:", "Gisela")
    is("Most of the earth's atmosphere consists of this gas.", "N")
    is("Most of the original American settlers were from what country?", "England")
    is("Mother Teresa was a _____ who did a lot of charity.", "Nun")
    is("Muhammad Ali became famous through which sport?", "Boxing")
    is("Napoleon Bonaparte was the famous emperor of _______.", "France")
    is("Nelson Mandela ___________________ before becoming the first President of democratic South Africa in 1994?", "spent over 20 years in jail")
    is("Nelson Mandela is from where?", "South Africa")
    is("Pablo Picasso is famous for his what?", "Art")
    is("President Thomas Jefferson made what large purchase to buy American a lot of new territory?", "Louisiana Purchase")
    is("Quandary", "a state of perplexity or uncertainty")
    is("Sir Edward Halley is the Spiral�s most famous:", "Aztecosaurologist")
    is("Sumner Fieldgold twice asks you to recover what for him?", "Shrubberies")
    is("The American Revolution was against the ________, the English army.", "Red Coats")
    is("The Swallows of Caliburn migrate to Avalon from where each year?", "Zafaria and Marleybone")
    is("The Swordsman Destreza was killed by:", "A Gorgon")
    is("The symbol 'Au' refers to which chemical element?", "Gold")
    is("The symbol 'Co' refers to which chemical element?", "Cobalt")
    is("The symbol 'Cu' refers to which chemical element?", "Copper")
    is("The symbol 'F' refers to which chemical element?", "Fluorine")
    is("The symbol 'H' refers to which chemical element?", "Hydrogen")
    is("The symbol 'Pb' refers to which chemical element?", "Lead")
    is("The symbol 'S' refers to which chemical element?", "Sulfur")
    is("This element helps give plants the energy they need to grow.", "P")
    is("This element is the building block of life.", "C")
    is("This element was discovered by Hans Christian Oersted in 1825.", "Al")
    is("This element was discovered by Joseph Priestly and Carl Scheele in 1774.", "O")
    is("This element when combined with Chlorine makes table salt.", "Na")
    is("This famous American colony is in modern Massachusetts.", "Plymouth")
    is("This famous display against England's taxation threw a luxury item into the sea.", "Boston Tea Party")
    is("Thomas Jefferson wrote which famous US document?", "The Declaration of Independence")
    is("What book was Anna Flameright accused of stealing?", "Advanced Flameology")
    is("What countries can play Wizard101?", "All the above")
    is("What currency do KingsIsle MMO games use?", "Crowns")
    is("What did Abigail Dolittle accuse Wadsworth of stealing?", "Genuine Imitation Golden Ruby")
    is("What did Prospector Zeke lose in Marleybone?", "The Stray Cats")
    is("What event is Abigail Doolittle sending out invitations for?", "Policeman's Ball")
    is("What is a very common last name of the cats in Marleybone?", "O'Leary")
    is("What is the capital of Alaska?", "Juneau")
    is("What is the capital of Colorado", "Denver")
    is("What is the capital of Colorado?", "Denver")
    is("What is the capital of Delaware?", "Dover")
    is("What is the capital of Georgia?", "Atlanta")
    is("What is the capital of Hawaii?", "Honolulu")
    is("What is the capital of Indiana", "Indianapolis")
    is("What is the capital of Indiana?", "Indianapolis")
    is("What is the capital of Kentucky?", "Frankfort")
    is("What is the capital of Louisiana?", "Baton Rouge")
    is("What is the capital of Maryland", "Annapolis")
    is("What is the capital of Massachusetts?", "Boston")
    is("What is the capital of Michigan", "Lansing")
    is("What is the capital of Minnesota?", "Saint Paul")
    is("What is the capital of Nebraska", "Lincoln")
    is("What is the capital of Nevada", "Carson City")
    is("What is the capital of New Jersey?", "Trenton")
    is("What is the capital of New Mexico?", "Santa Fe")
    is("What is the capital of Ohio?", "Columbus")
    is("What is the capital of Oklahoma", "Oklahoma City")
    is("What is the capital of Pennsylvania?", "Harrisburg")
    is("What is the capital of South Dakota", "Pierre")
    is("What is the capital of Tennessee", "Nashville")
    is("What is the capital of Texas", "Austin")
    is("What is the capital of Utah", "Salt Lake City")
    is("What is the capital of Utah?", "Salt Lake City")
    is("What is the capital of Vermont?", "Montpelier")
    is("What is the capital of Washington?", "Olympia")
    is("What is the capital of West Virginia", "Charleston")
    is("What is the capital of West Virginia?", "Charleston")
    is("What is the capital of Wisconsin?", "Madison")
    is("What is the capital of Wyoming?", "Cheyenne")
    is("What is the shape on the weather vanes in the Shopping District?", "Half moon/moon")
    is("What is the state bird of Arizona?", "Cactus Wren")
    is("What is the state bird of Connecticut?", "American Robin")
    is("What is the state bird of Hawaii?", "Nene")
    is("What is the state bird of Idaho?", "Mountain Bluebird")
    is("What is the state bird of Illinois?", "Cardinal")
    is("What is the state bird of Kansas?", "Western Meadowlark")
    is("What is the state bird of Maine?", "Black-Capped Chickadee")
    is("What is the state bird of Massachusetts?", "Black-Capped Chickadee")
    is("What is the state bird of Michigan?", "American Robin")
    is("What is the state bird of Minnesota?", "Common Loon")
    is("What is the state bird of Mississippi?", "Mockingbird")
    is("What is the state bird of Missouri?", "Eastern Bluebird")
    is("What is the state bird of Nebraska?", "Western Meadowlark")
    is("What is the state bird of New York?", "Eastern Bluebird")
    is("What is the state bird of Ohio?", "Cardinal")
    is("What is the state bird of Oklahoma?", "Scissor-Tailed Flycatcher")
    is("What is the state bird of South Dakota?", "Ring-Necked Pheasant")
    is("What is the state bird of Tennessee?", "Mockingbird")
    is("What is the state bird of Texas?", "Mockingbird")
    is("What is the state bird of Utah?", "California Gull")
    is("What is the state bird of West Virginia?", "Cardinal")
    is("What is the state bird of Wyoming?", "Western Meadowlark")
    is("What is the symbol for Potassium?", "K")
    is("What level must you be to wear Dragonspyre crafted clothing?", "33")
    is("What sort of beverage is served in Air Dales Hideaway?", "Root Beer")
    is("What style of artifacts are in the Royal Museum?", "Krokotopian")
    is("What time does the clock always read in Marleybone?", "1:55")
    is("What transports you from place to place in Marleybone?", "Hot Air Balloons")
    is("What two names are on the Statues in the Marleybone cathedral?", "Saint Bernard and Saint Hubert")
    is("What was the name of KingsIsle's first game?", "Wizard101")
    is("What was the name of the first charity Mount created by KingsIsle called?", "Meowmodon")
    is("What year did KingsIsle launch Pirate101?", "2012")
    is("What year did KingsIsle launch Wizard101?", "2008")
    is("What year did KingsIsle's Wizard101 get nominated for the MMO Hall of Fame?", "2014")
    is("What year did the British surrender in the American Revolution?", "1781")
    is("What year was the Declaration of Independence signed?", "1776")
    is("Where has Pharenor been imprisoned?", "Skythorn Tower")
    is("Where was President Abraham Lincoln assassinated?", "The Theatre")
    is("Which Plano charity has KingsIsle donated to?", "Children' Medical Center at Legacy in Plano")
    is("Which Queen is mentioned in the Marleybone book \"The Golden Age\"?", "Ellen")
    is("Which celebrity composed music for a KingsIsle game?", "Nick Jonas")
    is("Which early tax act made American settlers very angry pre-revolution?", "Stamp Act of 1765")
    is("Which element has a reddish color in a gas and liquid state?", "Br")
    is("Which natural resource was a large reason many Americans choose to journey westward in the 1800's?", "Gold")
    is("Which of these elements is NOT considered a Metalloid.", "Sn")
    is("Which of these elements is considered a Metal.", "Fe")
    is("Which of these folks can you find in the Royal Museum?", "Clancy Pembroke")
    is("Which state is known as the \"Aloha State?\"", "Hawaii")
    is("Which state is known as the \"Beehive State?\"", "Utah")
    is("Which state is known as the \"Bluegrass State?\"", "Kentucky")
    is("Which state is known as the \"Empire State?\"", "New York")
    is("Which state is known as the \"First State?\"", "Delaware")
    is("Which state is known as the \"Golden State?\"", "California")
    is("Which state is known as the \"Great Lakes State?\"", "Michigan")
    is("Which state is known as the \"Magnolia State?\"", "Mississippi")
    is("Which state is known as the \"Pelican State?\"", "Louisiana")
    is("Which state is known as the \"Prairie State?\"", "Illinois")
    is("Which state is known as the \"Silver State?\"", "Nevada")
    is("Which state is known as the \"Volunteer State?\"", "Tennessee")
    is("Which two amendments make up the Reconstruction Acts of 1867 and give African Americans additional freedoms?", "Fourteenth and Fifteenth")
    is("Which two ammendments make up the Reconstruction Acts of 1867 and give African Americans additional freedoms?", "Fourteenth and Fifteenth")
    is("Who Is NOT a member of the Council of Light?", "Cyrus Drake")
    is("Who composed Blue Danube?", "Strauss")
    is("Who composed Dance of the Sugar-Plum Fairy?", "Tchaikovsky")
    is("Who composed Eine Kleine Nachtmusik: Allegro?", "Mozart")
    is("Who composed Four Seasons?", "Vivaldi")
    is("Who composed Fur Elise?", "Beethoven")
    is("Who composed Hungarian Rhapsody No. 2?", "Liszt")
    is("Who composed In The Hall of the Mountain King?", "Grieg")
    is("Who composed Moonlight Sonata?", "Beethoven")
    is("Who composed Ode to Joy?", "Beethoven")
    is("Who composed Ride of the Valkyries?", "Wagner")
    is("Who composed Sorcerer's Apprentice?", "Dukas")
    is("Who composed Toccata and Fugue in D Minor?", "Bach")
    is("Who did the United States purchase Alaska from?", "Russia")
    is("Who grants the first Shadow Magic spell?", "Sophia DarkSide")
    is("Who is Bill Tanner's sister?", "Sarah Tanner")
    is("Who is Haraku Yip's apprentice?", "Binh Hoa")
    is("Who is not an officer you'll find around Marleybone?", "Officer Digmore")
    is("Who is the dangerous criminal that is locked up, but escapes from Newgate Prison?", "Meowiarty")
    is("Who makes the harpsicord for Shelus?", "Gretta Darkkettle")
    is("Who needs the healing potion from Master Yip?", "Binh Hoa")
    is("Who taunts: Why I oughta knock you to the moon, you pesky little creep!", "Mugsy")
    is("Who tells you: \"A shield is just as much a weapon as the sword.\"", "Mavra Flamewing")
    is("Who tries to raise a Gorgon Army?", "Phorcys")
    is("Who was Margaret Thatcher?", "British Prime Minister")
    is("Who was the 10th president of the United States?", "John Tyler")
    is("Who was the 11th president of the United States?", "James K. Polk")
    is("Who was the 12th president of the United States?", "Zachary Taylor")
    is("Who was the 14th president of the United States?", "Franklin Pierce")
    is("Who was the 16th president of the United States?", "Abraham Lincoln")
    is("Who was the 18th president of the United States?", "Ulysses S. Grant")
    is("Who was the 1st president of the United States?", "George Washington")
    is("Who was the 20th president of the United States?", "James A. Garfield")
    is("Who was the 21st president of the United States?", "Chester A. Arthur")
    is("Who was the 22nd president of the United States?", "Grover Cleveland")
    is("Who was the 23rd president of the United States?", "Benjamin Harrison")
    is("Who was the 24th president of the United States?", "Grover Cleveland")
    is("Who was the 26th president of the United States?", "Theodore Roosevelt")
    is("Who was the 27th president of the United States?", "William Howard Taft")
    is("Who was the 28th president of the United States?", "Woodrow Wilson")
    is("Who was the 29th president of the United States?", "Warren G. Harding")
    is("Who was the 2nd president of the United States?", "John Adams")
    is("Who was the 30th president of the United States?", "Calvin Coolidge")
    is("Who was the 31st president of the United States?", "Herbert Hoover")
    is("Who was the 32nd president of the United States?", "Franklin D. Roosevelt")
    is("Who was the 33rd president of the United States?", "Harry S. Truman")
    is("Who was the 36th president of the United States?", "Lyndon B. Johnson")
    is("Who was the 38th president of the United States?", "Gerald Ford")
    is("Who was the 39th president of the United States?", "Jimmy Carter")
    is("Who was the 3rd president of the United States?", "Thomas Jefferson")
    is("Who was the 41st president of the United States?", "George H. W. Bush")
    is("Who was the 42nd president of the United States?", "Bill Clinton")
    is("Who was the 44th president of the United States?", "Barack Obama")
    is("Who was the 4th president of the United States?", "James Madison")
    is("Who was the 8th president of the United States?", "Martin Van Buren")
    is("Who wrote 1984?", "George Orwell")
    is("Who wrote Gone with the Wind?", "Margaret Mitchell")
    is("Who wrote Lolita?", "Vladimir Nabokov")
    is("Who wrote Lord of the Flies?", "William Golding")
    is("Who wrote Mrs. Dalloway?", "Virginia Woolf")
    is("Who wrote On the Road?", "Jack Kerouac")
    is("Who wrote One Flew Over the Cuckoo's Nest?", "Ken Kesey")
    is("Who wrote The Grapes of Wrath?", "John Steinbeck")
    is("Who wrote The Heart is a Lonely Hunter?", "Carson McCullers")
    is("Who wrote The Sun Also Rises?", "Ernest Hemingway")
    is("Who wrote Their Eyes Were Watching God?", "Zora Neale Hurston")
    is("Who wrote Watchmen?", "Alan Moore")
    is("Winston Churchill was prime minister of Britian during which war?", "World War II")

})();
